dist: trusty

addons:
  apt:
    packages:
      - libssl1.0.0

language: python
python:
  - '3.6'

install:
  - 'pip install pipenv'
  - bash scripts/_install.sh

script:
  - bash scripts/_daily.sh

branches:
  only:
    - dark

cache:
  packages: yes
  directories:
    - $HOME/virtualenvs
    - $HOME/.local/share/virtualenvs
