language: python
python:
  - '3.6'

install:
  - 'pip install pipenv'
  - bash scripts/_install.sh

script:
  - bash scripts/_daily.sh

branches:
  only:
    - dawn

cache:
  packages: yes
  directories:
    - $HOME/virtualenvs
    - $HOME/.local/share/virtualenvs
